[package]
name = "vga_buffer"
version = "0.1.0"
authors = ["Andreas Bigger <abigger@nascent.xyz>"]
edition = "2018"

[dependencies]
volatile = "0.2.6"
lazy_static = { version = "1.0", features = ["spin_no_std"] }
spin = "0.5.2"