[unstable]
build-std-features = ["compiler-builtins-mem"] # Use compiler builtins' memory-related intrinsics
build-std = ["core", "compiler_builtins"] # Recompile core and compiler_builtins libraries for freestanding host triple
