# .cargo/config.toml

[build]
target = "x86-64-blog-os.json" # Override default cargo build target

[unstable]
build-std-features = ["compiler-builtins-mem"] # Use compiler builtins' memory-related intrinsics
build-std = ["core", "compiler_builtins"] # Recompile core and compiler_builtins libraries for freestanding host triple

[target.'cfg(target_os = "none")']
runner = "bootimage runner"