# .cargo/config.toml

# recompile core and compiler_builtins libraries for freestanding host triple
[unstable]
build-std-features = ["compiler-builtins-mem"] # Use compiler builtins' memory-related intrinsics
build-std = ["core", "compiler_builtins"]